package entidades;

public class TODO {
    // APAGAR ESSA CLASSE E CRIAR 6 CLASSES DIFERENTES
    // DENTRE ELAS: EVENTO(ABSTRACT), EVENTOFERIADO, EVENTOSHOW, EVENTOIGREJA, EVENTOPALESTRA, EVENTOFORMATURA, EVENTOREUNIAO 
}
